
germanyCities = {
    "A": "Augsburg",
    "AA": "Ostalbkreis (Aalen)",
    "AB": "Aschaffenburg",
    "ABG": "Altenburger Land",
    "ABI": "Anhalt-Bitterfeld",
    "AC": "Aachen",
    "AE": "Auerbach",
    "AH": "Ahaus",
    "AIB": "Bad Aibling",
    "AIC": "Aichach-Friedberg",
    "AK": "Altenkirchen",
    "AL": "Altena",
    "ALF": "Alfeld (Leine)",
    "ALS": "Alsfeld",
    "ALZ": "Alzenau",
    "AM": "Amberg",
    "AN": "Ansbach",
    "ANA": "Annaberg",
    "ANG": "Angermünde",
    "ANK": "Anklam",
    "AÖ": "Altötting",
    "AP": "Apolda",
    "APD": "Apolda",
    "ARN": "Arnstadt",
    "ART": "Artern",
    "AS": "Amberg-Sulzbach",
    "ASL": "Aschersleben",
    "ASZ": "Aue-Schwarzenberg",
    "AT": "Altentreptow",
    "AU": "Aue",
    "AUR": "Aurich",
    "AW": "Ahrweiler",
    "AZ": "Alzey-Worms",
    "AZE": "Anhalt-Zerbst",
    "B": "Berlin",
    "BA": "Bamberg",
    "BAD": "Baden-Baden",
    "BAR": "Barnim",
    "BB": "Böblingen",
    "BBG": "Bernburg",
    "BC": "Biberach",
    "BCH": "Buchen (Odenwald)",
    "BD": "Büdingen",
    "BE": "Beckum",
    "BED": "Benediktbeuern",
    "BER": "Bernau bei Berlin",
    "BF": "Burgdorf",
    "BGD": "Berchtesgadener Land",
    "BGL": "Berchtesgadener Land",
    "BI": "Bielefeld",
    "BID": "Biedenkopf",
    "BIN": "Bingen am Rhein",
    "BIR": "Birkenfeld",
    "BIT": "Bitburg-Prüm",
    "BIW": "Bischofswerda",
    "BK": "Bördekreis",
    "BL": "Baden-Württemberg (Balingen)",
    "BLB": "Bad Berleburg",
    "BM": "Bergheim",
    "BN": "Bonn",
    "BO": "Bochum",
    "BÖ": "Börde",
    "BOH": "Bocholt",
    "BOR": "Borken",
    "BOT": "Bottrop",
    "BRA": "Brake",
    "BRB": "Brandenburg an der Havel",
    "BRG": "Burg bei Magdeburg",
    "BRK": "Bad Brückenau",
    "BRL": "Braunlage",
    "BRV": "Bremervörde",
    "BS": "Braunschweig",
    "BT": "Bayreuth",
    "BÜD": "Büdingen",
    "BÜS": "Büsingen am Hochrhein",
    "BÜZ": "Bützow",
    "BW": "Blieskastel",
    "BWL": "Böblingen",
    "BY": "Bayern",
    "BZ": "Bautzen",
    "C": "Chemnitz",
    "CA": "Calau",
    "CAS": "Castrop-Rauxel",
    "CB": "Cottbus",
    "CE": "Celle",
    "CHA": "Cham",
    "CLP": "Cloppenburg",
    "CLZ": "Clausthal-Zellerfeld",
    "CO": "Coburg",
    "COC": "Cochem-Zell",
    "COE": "Coesfeld",
    "CR": "Crailsheim",
    "CW": "Calw",
    "D": "Düsseldorf",
    "DA": "Darmstadt",
    "DAH": "Dachau",
    "DAN": "Lüchow-Dannenberg",
    "DAU": "Daun",
    "DBR": "Bad Doberan",
    "DD": "Dresden",
    "DE": "Dessau",
    "DEG": "Deggendorf",
    "DEL": "Delmenhorst",
    "DGF": "Dingolfing-Landau",
    "DH": "Diepholz",
    "DI": "Dieburg",
    "DIL": "Dillingen",
    "DIN": "Dinslaken",
    "DIZ": "Diez",
    "DKB": "Dinkelsbühl",
    "DL": "Döbeln",
    "DLG": "Dillingen",
    "DM": "Demmin",
    "DN": "Düren",
    "DO": "Dortmund",
    "DON": "Donau-Ries",
    "DU": "Duisburg",
    "DÜW": "Bad Dürkheim",
    "DW": "Dippoldiswalde",
    "DY": "Düren",
    "DZ": "Delitzsch",
    "E": "Essen",
    "EA": "Eisenach",
    "EBE": "Ebersberg",
    "EBN": "Ebern",
    "EBS": "Ebermannstadt",
    "ECK": "Eckernförde",
    "ED": "Erding",
    "EE": "Elbe-Elster",
    "EF": "Erfurt",
    "EG": "Eggenfelden",
    "EH": "Eichstätt",
    "EI": "Eichstätt",
    "EIC": "Eichsfeld",
    "EIH": "Eichstätt",
    "EIL": "Eilenburg",
    "EIN": "Einbeck",
    "EL": "Emsland",
    "EM": "Emmendingen",
    "EMD": "Emden",
    "EMS": "Rhein-Lahn-Kreis",
    "EN": "Ennepe-Ruhr-Kreis",
    "ER": "Erlangen",
    "ERB": "Odenwaldkreis",
    "ERH": "Erlangen-Höchstadt",
    "ERK": "Erkelenz",
    "ERZ": "Erzgebirgskreis",
    "ES": "Esslingen",
    "ESB": "Eschenbach",
    "ESW": "Eschwege",
    "EU": "Euskirchen",
    "EW": "Eberswalde",
    "F": "Frankfurt am Main",
    "FB": "Friedberg",
    "FD": "Fulda",
    "FDS": "Freudenstadt",
    "FF": "Frankfurt (Oder)",
    "FFB": "Fürstenfeldbruck",
    "FG": "Freiberg",
    "FI": "Finsterwalde",
    "FL": "Flensburg",
    "FLÖ": "Flöha",
    "FN": "Friedrichshafen",
    "FO": "Forchheim",
    "FOR": "Forst (Lausitz)",
    "FR": "Freiburg im Breisgau",
    "FRG": "Freyung-Grafenau",
    "FRI": "Friesland",
    "FRW": "Bad Freienwalde",
    "FS": "Freising",
    "FT": "Frankenthal",
    "FTL": "Freital",
    "FÜ": "Fürth",
    "G": "Gera",
    "GA": "Gardelegen",
    "GAP": "Garmisch-Partenkirchen",
    "GC": "Glauchau",
    "GD": "Gmünd",
    "GDB": "Bad Doberan",
    "GE": "Gelsenkirchen",
    "GEL": "Geldern",
    "GEM": "Gemünden am Main",
    "GER": "Germersheim",
    "GF": "Gifhorn",
    "GG": "Groß-Gerau",
    "GHA": "Geithain",
    "GHC": "Gräfenhainichen",
    "GI": "Gießen",
    "GK": "Geilenkirchen",
    "GL": "Bergisch Gladbach",
    "GLA": "Gladbeck",
    "GM": "Gummersbach",
    "GMN": "Grimmen",
    "GN": "Gelnhausen",
    "GNT": "Genthin",
    "GOA": "Sankt Goar",
    "GOH": "Sankt Goarshausen",
    "GP": "Göppingen",
    "GR": "Görlitz",
    "GRH": "Großenhain",
    "GRI": "Griesbach",
    "GRM": "Grimma",
    "GRZ": "Greiz",
    "GS": "Goslar",
    "GT": "Gütersloh",
    "GTH": "Gotha",
    "GÜ": "Güstrow",
    "GUB": "Guben",
    "GUN": "Gunzenhausen",
    "GVM": "Grevesmühlen",
    "GW": "Greifswald",
    "GY": "Geithain",
    "H": "Hannover",
    "HA": "Hagen",
    "HAL": "Halle",
    "HAM": "Hamm",
    "HAS": "Haßberge",
    "HB": "Bremen",
    "HBN": "Hildburghausen",
    "HBS": "Halberstadt",
    "HC": "Hainichen",
    "HCH": "Hechingen",
    "HD": "Heidelberg",
    "HDH": "Heidenheim",
    "HDL": "Haldensleben",
    "HE": "Helmstedt",
    "HEB": "Hersbruck",
    "HEF": "Hersfeld-Rotenburg",
    "HEI": "Heide",
    "HEL": "Helmstedt",
    "HER": "Herne",
    "HET": "Hettstedt",
    "HF": "Herford",
    "HG": "Bad Homburg",
    "HGN": "Hagenow",
    "HGW": "Greifswald",
    "HH": "Hamburg",
    "HI": "Hildesheim",
    "HIG": "Heiligenstadt",
    "HL": "Lübeck",
    "HM": "Hameln",
    "HMU": "Uecker-Randow",
    "HN": "Heilbronn",
    "HO": "Hof",
    "HOG": "Homberg",
    "HOL": "Holzminden",
    "HOM": "Homburg",
    "HOT": "Hohenstein-Ernstthal",
    "HP": "Heppenheim",
    "HR": "Homberg (Efze)",
    "HRO": "Rostock",
    "HS": "Heinsberg",
    "HSK": "Hochsauerlandkreis",
    "HST": "Stralsund",
    "HU": "Hanau",
    "HV": "Havelberg",
    "HVL": "Havelland",
    "HWI": "Wismar",
    "HX": "Höxter",
    "HY": "Hoyerswerda",
    "HZ": "Harz",
    "IGB": "St. Ingbert",
    "IK": "Ilm-Kreis",
    "ILL": "Illertissen",
    "IN": "Ingolstadt",
    "IZ": "Itzehoe",
    "J": "Jena",
    "JE": "Jessen (Elster)",
    "JL": "Jerichower Land",
    "JÜL": "Jülich",
    "K": "Köln",
    "KA": "Karlsruhe",
    "KB": "Korbach",
    "KC": "Kronach",
    "KE": "Kempten",
    "KEH": "Kelheim",
    "KF": "Kaufbeuren",
    "KG": "Bad Kissingen",
    "KH": "Bad Kreuznach",
    "KI": "Kiel",
    "KIB": "Kirchheimbolanden",
    "KL": "Kaiserslautern",
    "KLE": "Kleve",
    "KLZ": "Klötze",
    "KM": "Kamenz",
    "KN": "Konstanz",
    "KO": "Koblenz",
    "KÖN": "Bad Königshofen",
    "KÖT": "Köthen",
    "KR": "Krefeld",
    "KS": "Kassel",
    "KT": "Kitzingen",
    "KU": "Kulmbach",
    "KÜN": "Künzelsau",
    "KUS": "Kusel",
    "KW": "Königs Wusterhausen",
    "KY": "Kyritz",
    "KYF": "Kyffhäuserkreis",
    "L": "Leipzig",
    "LA": "Landshut",
    "LAU": "Lauf an der Pegnitz",
    "LB": "Ludwigsburg",
    "LBS": "Lobenstein",
    "LBZ": "Lübz",
    "LD": "Landau in der Pfalz",
    "LDK": "Lahn-Dill-Kreis",
    "LDS": "Dahme-Spreewald",
    "LEO": "Leonberg",
    "LER": "Leer",
    "LEV": "Leverkusen",
    "LG": "Lüneburg",
    "LH": "Lüdinghausen",
    "LI": "Lindau",
    "LIB": "Liebenwerda",
    "LIF": "Lichtenfels",
    "LIP": "Lippe",
    "LL": "Landsberg am Lech",
    "LM": "Limburg an der Lahn",
    "LÖ": "Lörrach",
    "LOS": "Oder-Spree",
    "LP": "Lippstadt",
    "LR": "Lahr",
    "LRO": "Bad Doberan",
    "LU": "Ludwigshafen",
    "LÜN": "Lünen",
    "LUP": "Ludwigslust-Parchim",
    "LWL": "Ludwigslust",
    "M": "München",
    "MA": "Mannheim",
    "MAB": "Marienberg",
    "MAI": "Mainburg",
    "MAK": "Marktredwitz",
    "MAL": "Mallersdorf",
    "MB": "Miesbach",
    "MC": "Malchin",
    "MD": "Magdeburg",
    "ME": "Mettmann",
    "MEI": "Meißen",
    "MEK": "Mittlerer Erzgebirgskreis",
    "MG": "Mönchengladbach",
    "MGH": "Möckmühl",
    "MGN": "Meiningen",
    "MH": "Mülheim an der Ruhr",
    "MHL": "Mühlhausen",
    "MI": "Minden",
    "MIL": "Miltenberg",
    "MK": "Märkischer Kreis",
    "MKG": "Markgröningen",
    "ML": "Mansfeld-Südharz",
    "MM": "Memmingen",
    "MN": "Mindelheim",
    "MO": "Moers",
    "MOD": "Marktoberdorf",
    "MOL": "Märkisch-Oderland",
    "MOS": "Mosbach",
    "MQ": "Merseburg-Querfurt",
    "MR": "Marburg",
    "MS": "Münster",
    "MSH": "Mansfeld-Südharz",
    "MSP": "Main-Spessart",
    "MST": "Mecklenburg-Strelitz",
    "MTK": "Main-Taunus-Kreis",
    "MTL": "Muldentalkreis",
    "MÜ": "Mühldorf am Inn",
    "MÜR": "Müritz",
    "MW": "Mittweida",
    "MY": "Mayen",
    "MYK": "Mayen-Koblenz",
    "MZ": "Mainz",
    "MZG": "Merzig",
    "N": "Nürnberg",
    "NB": "Neubrandenburg",
    "ND": "Neuburg-Schrobenhausen",
    "NDH": "Nordhausen",
    "NE": "Neuss",
    "NEA": "Neustadt an der Aisch",
    "NEB": "Nebra",
    "NEC": "Neustadt bei Coburg",
    "NEN": "Neunburg",
    "NES": "Bad Neustadt an der Saale",
    "NEW": "Neustadt an der Waldnaab",
    "NF": "Nordfriesland",
    "NH": "Neuhaus am Rennweg",
    "NI": "Nienburg/Weser",
    "NK": "Neunkirchen",
    "NL": "Naumburg",
    "NM": "Neumarkt in der Oberpfalz",
    "NMB": "Naumburg",
    "NMS": "Neumünster",
    "NOH": "Nordhorn",
    "NOL": "Niederschlesischer Oberlausitzkreis",
    "NOM": "Northeim",
    "NOR": "Norden",
    "NP": "Neuruppin",
    "NR": "Neuwied",
    "NRW": "Nordrhein-Westfalen",
    "NT": "Nürtingen",
    "NU": "Neu-Ulm",
    "NVP": "Nordvorpommern",
    "NW": "Neustadt an der Weinstraße",
    "NWM": "Nordwestmecklenburg",
    "NY": "Niesky",
    "NZ": "Neustrelitz",
    "OA": "Oberallgäu",
    "OAL": "Ostallgäu",
    "OB": "Oberhausen",
    "OD": "Bad Oldesloe",
    "OE": "Olpe",
    "OF": "Offenbach",
    "OG": "Offenburg",
    "OH": "Ostholstein",
    "OHA": "Osterode am Harz",
    "ÖHR": "Öhringen",
    "OHV": "Oberhavel",
    "OHZ": "Osterholz-Scharmbeck",
    "OL": "Oldenburg",
    "OPR": "Ostprignitz-Ruppin",
    "OS": "Osnabrück",
    "OSL": "Oberspreewald-Lausitz",
    "OVP": "Ostvorpommern",
    "P": "Potsdam",
    "PA": "Passau",
    "PAF": "Pfaffenhofen an der Ilm",
    "PAN": "Rottal-Inn",
    "PB": "Paderborn",
    "PCH": "Parchim",
    "PE": "Peine",
    "PEG": "Pegnitz",
    "PF": "Pforzheim",
    "PI": "Pinneberg",
    "PIR": "Pirna",
    "PK": "Pritzwalk",
    "PL": "Plauen",
    "PLÖ": "Plön",
    "PM": "Potsdam-Mittelmark",
    "PN": "Pößneck",
    "PR": "Prignitz",
    "PRÜ": "Prüm",
    "PS": "Pirmasens",
    "PW": "Prenzlau",
    "PZ": "Prenzlau",
    "QFT": "Querfurt",
    "QLB": "Quedlinburg",
    "R": "Regensburg",
    "RA": "Rastatt",
    "RC": "Reichenbach",
    "RD": "Rendsburg",
    "RDG": "Ribnitz-Damgarten",
    "RE": "Recklinghausen",
    "REG": "Regen",
    "REH": "Rehau",
    "RG": "Riesa",
    "RH": "Roth",
    "RI": "Rinteln",
    "RID": "Riedenburg",
    "RIE": "Riesa",
    "RL": "Rochlitz",
    "RM": "Rheinsberg",
    "RN": "Rathenow",
    "RO": "Rosenheim",
    "ROD": "Roding",
    "ROF": "Rotenburg",
    "ROK": "Rockenhausen",
    "ROL": "Rodalben",
    "ROS": "Rostock",
    "ROW": "Rotenburg",
    "RP": "Rheinland-Pfalz",
    "RPL": "Rheinland-Pfalz",
    "RS": "Remscheid",
    "RSL": "Roßlau",
    "RT": "Reutlingen",
    "RU": "Rudolstadt",
    "RÜD": "Rüdesheim",
    "RÜG": "Rügen",
    "RV": "Ravensburg",
    "RW": "Rottweil",
    "RZ": "Ratzeburg",
    "S": "Stuttgart",
    "SAB": "Saarburg",
    "SAD": "Schwandorf",
    "SAW": "Salzwedel",
    "SB": "Saarbrücken",
    "SBK": "Schönebeck",
    "SC": "Schwabach",
    "SCZ": "Schleiz",
    "SDH": "Sondershausen",
    "SDL": "Stendal",
    "SDT": "Schwedt",
    "SE": "Bad Segeberg",
    "SEB": "Sebnitz",
    "SEE": "Seelow",
    "SEF": "Scheinfeld",
    "SEL": "Selb",
    "SFB": "Senftenberg",
    "SFT": "Staßfurt",
    "SG": "Solingen",
    "SGH": "Sangerhausen",
    "SHA": "Schwäbisch Hall",
    "SHG": "Stadthagen",
    "SHK": "Saale-Holzland-Kreis",
    "SHL": "Suhl",
    "SI": "Siegen",
    "SIG": "Sigmaringen",
    "SIM": "Simmern",
    "SK": "Saalkreis",
    "SL": "Schleswig",
    "SLE": "Schleiden",
    "SLF": "Saalfeld",
    "SLK": "Salzlandkreis",
    "SLS": "Saarlouis",
    "SM": "Schmalkalden",
    "SÖM": "Sömmerda",
    "SON": "Sonneberg",
    "SP": "Speyer",
    "SPB": "Spremberg",
    "SPN": "Spree-Neiße",
    "SR": "Straubing",
    "SRB": "Strausberg",
    "SRO": "Stadtroda",
    "ST": "Steinfurt",
    "STA": "Starnberg",
    "STB": "Stolzenau",
    "STD": "Stade",
    "STE": "Steinheim",
    "STL": "Stollberg",
    "SU": "Siegburg",
    "SÜW": "Südliche Weinstraße",
    "SW": "Schweinfurt",
    "SWA": "Schwabmünchen",
    "SY": "Syke",
    "SZ": "Salzgitter",
    "SZB": "Schwarzenberg",
    "TBB": "Tauberbischofsheim",
    "TDO": "Torgau-Oschatz",
    "TET": "Teterow",
    "TF": "Teltow-Fläming",
    "TG": "Tuttlingen",
    "THL": "Thüringen",
    "THW": "Thalheim",
    "THW": "Thale",
    "THW": "Thüringen",
    "TIR": "Tirschenreuth",
    "TO": "Torgau",
    "TÖL": "Bad Tölz-Wolfratshausen",
    "TP": "Templin",
    "TR": "Trier",
    "TS": "Traunstein",
    "TÜ": "Tübingen",
    "TUT": "Tuttlingen",
    "UE": "Uelzen",
    "UEM": "Ueckermünde",
    "UFF": "Uffenheim",
    "UH": "Unstrut-Hainich-Kreis",
    "UL": "Ulm",
    "UM": "Uckermark",
    "UN": "Unna",
    "USI": "Usingen",
    "VAI": "Vaihingen",
    "VB": "Vogelsbergkreis",
    "VEC": "Vechta",
    "VER": "Verden",
    "VG": "Vorpommern-Greifswald",
    "VIB": "Vilsbiburg",
    "VID": "Vilshofen",
    "VK": "Völklingen",
    "VS": "Villingen-Schwenningen",
    "W": "Wuppertal",
    "WA": "Waldeck",
    "WAF": "Warendorf",
    "WAK": "Wartburgkreis",
    "WAL": "Waldshut",
    "WAN": "Wanne-Eickel",
    "WAR": "Warburg",
    "WB": "Wittenberg",
    "WBS": "Worbis",
    "WDA": "Werdau",
    "WE": "Weimar",
    "WEN": "Weiden in der Oberpfalz",
    "WES": "Wesel",
    "WF": "Wolfenbüttel",
    "WHV": "Wilhelmshaven",
    "WI": "Wiesbaden",
    "WIL": "Wittlich",
    "WIS": "Wismar",
    "WIT": "Witten",
    "WK": "Wittstock",
    "WL": "Winsen (Luhe)",
    "WLG": "Wolgast",
    "WM": "Weilheim-Schongau",
    "WN": "Waiblingen",
    "WND": "Sankt Wendel",
    "WO": "Worms",
    "WOB": "Wolfsburg",
    "WOH": "Wolfhagen",
    "WOL": "Wolfratshausen",
    "WOR": "Bad Tölz-Wolfratshausen",
    "WOS": "Wolfstein",
    "WR": "Wernigerode",
    "WRN": "Waren (Müritz)",
    "WSF": "Weißenfels",
    "WST": "Westerstede",
    "WSW": "Wilsdruff",
    "WT": "Waldshut",
    "WTM": "Wittmund",
    "WTÜ": "Witzenhausen",
    "WÜ": "Würzburg",
    "WUG": "Weißenburg-Gunzenhausen",
    "WUN": "Wunsiedel",
    "WUR": "Wurzen",
    "WW": "Westerwaldkreis",
    "WZ": "Wetzlar",
    "X": "Xanten",
    "Y": "Ystad",
    "Z": "Zwickau",
    "ZE": "Zeitz",
    "ZEL": "Zell",
    "ZI": "Zittau",
    "ZIG": "Ziegenhain",
    "ZP": "Zschopau",
    "ZR": "Zeulenroda",
    "ZS": "Zossen",
    "ZW": "Zweibrücken",
    "ZZ": "Zeitz"
}

def germany(letters):
    if len(letters) > 3:
        AttributeError("The length of the license plate is too long")
    if len(letters) < 1:
        AttributeError("The length of the license plate is too short")

    if letters in germanyCities:
        return germanyCities[letters]
    
    return "City not found"

print(germany("THW"))